steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/dauren-pr/calctech_site:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/dauren-pr/calctech_site:latest']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=ct_user.enc
  - --plaintext-file=ct_user
  - --location=global
  - --keyring=calctech
  - --key=key1
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod 0700 ct_user
    ssh -o StrictHostKeyChecking=no -i ct_user user@35.224.168.117 "/home/user/refresh.sh"
