substitutions:
  _PROJECT_NAME: calctech
  _APP_NAME: site
  _REPO_NAME: gcr.io/calctechc/calctech_site
  _SERVER_URI: user@35.198.156.152

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - kms
      - decrypt
      - --ciphertext-file=server_ssh_key.enc
      - --plaintext-file=server_ssh_key
      - --location=global
      - --keyring=calctech
      - --key=key1
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        for digest in $(gcloud container images list-tags $_REPO_NAME --limit=999999 --filter="-tags:*" --format='get(digest)'); do
          gcloud container images delete -q --force-delete-tags "${_REPO_NAME}@${digest}"
        done
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_REPO_NAME:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_REPO_NAME:latest']
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod 0700 server_ssh_key
        ssh -o StrictHostKeyChecking=no -i server_ssh_key $_SERVER_URI "/home/user/refresh.sh"
  - name: 'gcr.io/cloud-builders/curl'
    args:
      - -X
      - POST
      - --data-urlencode
      - 'payload={"icon_emoji": ":sweat_drops:", "username": "$_PROJECT_NAME GCB", "attachments": [{"color": "#36a64f", "title": "$_APP_NAME", "text": "successfully deployed - $_APP_NAME"}]}'
      - https://hooks.slack.com/services/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
